num1 = float(input())
print(type(num1))
print(num1)
num2 = str(input())
print(type(num2))
print(num2)
num3 = int(input())
print(type(num3))
print(num3)
num = bool(input())
print(type(num))
print(num)
